version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:${lb_version}
    ${lb_ports}
    labels:
      io.rancher.scheduler.affinity:host_label: ${label_scheduling}
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: ${global_scheduling}